<?php

/**
 * Implements hook_entity_info_alter().
 */
function dlts_book_display_entity_info_alter(&$entity_info) {

  $entity_info['node']['view modes']['metadata'] = array(
    'label' => t('Metadata List'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['multivolbook'] = array(
    'label' => t('Multi Volume book'),
    'custom settings' => TRUE,
  );

}

/**
 * Implements hook_preprocess_node().
 */
function dlts_book_display_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'metadata') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__metadata';
  }

  if ($vars['view_mode'] == 'multivolbook') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__multivolbook';
  }

}

function dlts_book_display_views_pre_render(&$view) {
  if ($view->name == 'book_thumbnails') {
    // Here you can do any php you want to get the title you need for your view.
    // Depends on dlts_book_api
    if (function_exists('dlts_book_load') ){
      $book_node = dlts_book_load($view->args[0]);
      $view->build_info['title'] = $book_node->title;
    }
  }
}

/**
 * Implements hook_menu_alter.
 * Check access for forum menu item.
 */
function dlts_book_display_menu_alter(&$items) {
  $items['user/register']['access callback'] = FALSE;
  $items['user/password']['access callback'] = FALSE;
}
